# file: kafka.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  base.properties: |
    process.roles=broker,controller
    controller.listener.names=CONTROLLER
    listeners=INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
    listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
    inter.broker.listener.name=INTERNAL
    log.dirs=/var/lib/kafka/data
    controller.quorum.bootstrap.servers=kafka-0.kafka-service.kafka.svc.cluster.local:9093,kafka-1.kafka-service.kafka.svc.cluster.local:9093
    controller.quorum.voters=0@kafka-0.kafka-service.kafka.svc.cluster.local:9093,1@kafka-1.kafka-service.kafka.svc.cluster.local:9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: controller
      port: 9093
      protocol: TCP
      targetPort: 9093
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          command: ["sh", "-c"]
          args:
            - |
              set -e
              NODE_ID="$(hostname | awk -F'-' '{print $2}')"
              CLUSTER_ID="uhaGgVSiR3W05yPkn_pKgw"

              # Cấu hình ID
              echo "node.id=${NODE_ID}" >> /opt/kafka/config/server.properties

              # INTERNAL address
              INTERNAL_DNS="$(hostname).kafka-service.kafka.svc.cluster.local"

              # Cấu hình EXTERNAL IP và Port động
              # Node 0 -> Port 30092, Node 1 -> Port 30093
              PUBLIC_IP="${KAFKA_PUBLIC_IP}"   # 🔧 CHANGED: dùng PUBLIC IP cố định
              EXTERNAL_PORT=$((30092 + NODE_ID))

              sed -i '/^advertised.listeners/d' /opt/kafka/config/server.properties

              # QUAN TRỌNG: Advertised port phải là port public (30092/30093) chứ không phải 9094
              echo "advertised.listeners=INTERNAL://${INTERNAL_DNS}:9092,EXTERNAL://${PUBLIC_IP}:${EXTERNAL_PORT}" >> /opt/kafka/config/server.properties

              cat /kafka/config/base.properties >> /opt/kafka/config/server.properties

              if [ ! -f /var/lib/kafka/data/meta.properties ]; then
                /opt/kafka/bin/kafka-storage.sh format -t "${CLUSTER_ID}" -c /opt/kafka/config/server.properties
              fi
              exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
          env:
            - name: KAFKA_PUBLIC_IP
              value: "52.221.207.227"         # 🔧 CHANGED: PUBLIC IP của EC2
          ports:
            - containerPort: 9092 # INTERNAL
            - containerPort: 9094 # EXTERNAL
            - containerPort: 9093 # CONTROLLER
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/kafka/data
            - name: config
              mountPath: /kafka/config
      volumes:
        - name: config
          configMap:
            name: kafka-config
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-0.kafka-service.kafka.svc.cluster.local:9092,kafka-1.kafka-service.kafka.svc.cluster.local:9092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: kafka-ui
